version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: exam-mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: exam
        MYSQL_USER: exam
        MYSQL_PASSWORD: exam
    ports:
        - "3306:3306"

  redis:
    image: redis:6.2
    container_name: exam-redis
    ports:
        - "6379:6379"