server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exam
    username: exam
    password: exam
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # druid connection pool management
    druid:
      # Number of physical connections established during initialization
      initial-size: 5
      # Minimum number of idle connections in the pool
      min-idle: 5
      # Maximum number of connections in the pool
      max-active: 20
      # Maximum wait time to get a connection, in milliseconds
      max-wait: 60000
      # Check if the connection is valid when idle time exceeds timeBetweenEvictionRunsMillis during the connection request
      test-while-idle: true
      # Interval time for detection and basis for testWhileIdle execution
      time-between-eviction-runs-millis: 60000
      # Close the current connection if the difference between the last active time of the current connection and the current time exceeds this value (minimum survival time of connections in the pool)
      min-evictable-idle-time-millis: 30000
      # SQL used to check if the database connection is valid, must be a query statement (for Oracle, it is select 1 from dual)
      validation-query: select 'x'
      # Check if the connection is valid during the connection request, enabling it will reduce performance, default is true
      test-on-borrow: false
      # Check if the connection is valid when returning, enabling it will reduce performance, default is true
      test-on-return: false
      # Whether to cache preparedStatement, which is PSCache. PSCache significantly improves performance for databases that support cursors, such as Oracle. It is recommended to disable it in MySQL.
      pool-prepared-statements: false
      # Set monitoring statistics interceptors. Removing it will cause the monitoring interface SQL statistics to fail. Stat: monitoring statistics, Slf4j: log recording, wall: defense against SQL injection
      filters: stat,wall,slf4j
      # To enable PSCache, this value must be greater than 0. When greater than 0, poolPreparedStatements is automatically modified to true. In Druid, there is no issue with excessive memory usage of PSCache in Oracle. You can set this value larger, such as 100.
      max-pool-prepared-statement-per-connection-size: -1
      # Merge monitoring data of multiple DruidDataSources
      use-global-data-source-stat: true
      # Enable mergeSql feature through connectProperties; slow SQL records
      # connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      web-stat-filter:
        # Whether to enable StatFilter, default is true
        enabled: true
        # Add filter rules
        url-pattern: /*
        # Ignore filtering formats
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico

      stat-view-servlet:
        login-url: /druid/login
        # Whether to enable StatViewServlet, default is true
        enabled: false
        # Whether data can be reset
        reset-enable: false
        # When accessing the path /druid, it redirects to StatViewServlet
        url-pattern: /druid/*

        # The console requires a username and password to access, default is root
        login-username: druid
        login-password: druid

        # IP whitelist
        allow: 127.0.0.1
        # IP blacklist (when both exist, deny takes precedence over allow)
        deny:
  main:
    # Disable banner
    banner-mode: off
    # Allow circular references
    allow-circular-references: true
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 10s
      lettuce:
        pool:
          # Maximum number of connections in the pool, default is 8. A negative value means no limit.
          max-active: 8
          # Maximum blocking wait time in the pool (use a negative value to indicate no limit), default is -1
          max-wait: -1
          # Maximum number of idle connections in the pool, default is 8
          max-idle: 8
          # Minimum number of idle connections in the pool, default is 0
          min-idle: 0
  servlet:
    multipart:
      max-file-size: 5MB

mybatis-plus:
  global-config:
    # Disable banner
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case:
  type-aliases-package: com.hnv99.exam.model

jwt:
  secret: iosethaosiaekdarfhasjtslgnvioweaoirthaoitialtgasgnsakltghfhbrhnae
  expire: 604800000 # 7 days

# Fill in the configuration below for AliOSS before using
oss:
  endpoint:
  access-key-id:
  access-key-secret:
  bucket-name:

logging:
  level:
    root: info
    com.example: debug
